### ISSUE TITLE
Change Shim prefix to underscore suffix

### ISSUE THREAD

**Issue by anders9ustafsson** [cureos/shim#16]
Rather than naming a class for example `ShimPath`, use the original class name `Path` and place the Shim type in the `Shim.IO` namespace instead.

**Comment by anders9ustafsson** [comment]
After further consideration, I have reached the conclusion that it is better to use a different name for the complementary _Shim_ types.

A typical scenario that could very well lead to complications if the _Shim_ class has the same name as the class it is filling up for, but in another namespace, is a code line like this:

```
Assembly a = Assembly.GetExecutingAssembly();
```

`Assembly.GetExecutingAssembly()` would be located in the `Shim.Reflection` namespace, but it would return a `System.Reflection.Assembly` object. 

It will not be possible to specify any `using` directive. Either way, there will be confusion as to which `Assembly` class is being referenced.

Replacing the explicit variable declaration with the `var` keyword could be one solution if no other name clashes appear in the same source file. It would then be necessary to add `using Shim.Reflection`.

Qualified class naming could also be a solution, but might be tedious to get in place everywhere:

```
System.Reflection.Assembly a = Shim.Reflection.Assembly.GetExecutingAssembly();
```

The `Shim` prefix **is** an "unclean" solution, but some kind of different naming is anyway desirable to minimize the intrusion on the legacy code. The suggestion is then to rename the _Shim_ types to use a `_` suffix instead of the `Shim` prefix. The legacy code will have to be changed, but very little. And the new _Shim_ file naming will not intrude on the internal naming of base classes in the .NET libraries, where a `_` **prefix** is sometimes employed.

**Comment by cesarsouza** [comment]
Hi Anders,

I just wanted to let you know that there is a technique to refer to specific assemblies even if they have the same namespace. I am not sure if this would help in this case, but perhaps it might be useful to you.

The point is that, even if you have two assemblies with the same name in a solution, you can assign an alias for your assembly in the "References" section of the solution folder, and then you will be able to do things like:

```
  using shim:System.Reflection;
```

It is also possible to assign those aliases to normal .NET assemblies: http://stackoverflow.com/questions/27589528/how-to-create-an-extern-alias-to-mscorlib

**Comment by anders9ustafsson** [comment]
César,

many thanks for the valuable information. I am not sure if it can solve this particular problem, but I need to give it some more thought.

The problem I am facing is that I want to be able to access both the original class (`Assembly`) and the _Shim_ class (`Assembly_`) from the same source code file. If I give the _Shim_ class the same name as the original class, but place it in another namespace, I will have an issue with the `using` directive(s). I could use fully qualified declarations, i.e. `System.Reflection.Assembly` and `Shim.Reflection.Assembly` but that requires a lot of additional typing and will look confusing in code.

Since I am really only trying to "fill in" for some static methods missing in the PCL instance of the `Assembly` class, the cleanest solution I can think of right now is to use a class name that is close to but not identical to the original class, and to place the _Shim_ class in the same namespace. Then the editing required in the legacy code will be minimal, only add the underscore suffix to the class name in the relevant method invocations.

Or is there an approach that would be even less intrusive on the legacy code? I can't think of one, but I would be very grateful for other suggestions.

Best regards,
Anders
