### ISSUE TITLE
Compile error when referencing ZXing.NET 

### ISSUE THREAD

**Issue by Don2** [cureos/shim#23]
I get the following error when I try to compile when referencing ZXing.NET BarcodeReader.Decode method.

Does anyone know why?

The type 'System.Drawing.Bitmap' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'.

**Comment by anders9ustafsson** [comment]
But this must be an issue for the _ZXing.NET_ developers, or? Unless you have some more information explicitly tying the error to _Shim_, I recommend that you file an issue report [here](http://zxingnet.codeplex.com/workitem/list/basic) instead.

**Comment by Don2** [comment]
I'm evaluating this library with the view to purchasing a license for the Andoird platform, at least.
Do you have a working sample that I can test with.

**Comment by anders9ustafsson** [comment]
You can look for samples [here](https://github.com/cureos/accord-samples). There are two Android samples, one based on _Xamarin.Forms_ and one independent sample. Unfortunately, the independent _Wavelets_ sample have some issues with the _Shim.Drawing_ version it is using, but it should give you an idea of how to compose your own examples.

I have not examined _ZXing.NET_ in detail, but please be aware that the _Shim.Drawing_ libraries are designed primarily to support the `System.Drawing` calls in _AForge.NET_ and_Accord.NET_. _Shim.Drawing_ publicly exposes only a minimal subset of the `Bitmap` and `Color` classes in _System.Drawing_ and cannot generally be used as a full-blown replacement for the _System.Drawing_ assembly.
