### ISSUE TITLE
Timer.Dispose

### ISSUE THREAD

**Issue by NVentimiglia** [cureos/shim#28]
I am porting some code over and noticed that Timer.Dispose was not implemented. I see no equivalent.

**Comment by anders9ustafsson** [comment]
You are absolutely right, it is missing! I will add it ASAP and publish an updated NuGet package.

Many thanks for pointing this out!

/ Anders

**Comment by anders9ustafsson** [comment]
I have now published an update on NuGet where Timer.Dispose() is added. Please give it a try and see if it works as intended.
