### ISSUE TITLE
System.Net.Sockets

### ISSUE THREAD

**Issue by NVentimiglia** [cureos/shim#29]
I`m porting a websocket library and quickly realising that socket support in PCL is severely limited. I noticed that the System.Net.Sockets namespace included in this project, but, from the looks of it not fully implemented. What is the plan for including socket support ?

I should add, I found this project https://github.com/rdavisau/sockets-for-pcl however I dont feel like wrapping the socket to read/write string messages... and their own wrapper is confusing. Worse case I will just use the Dependency Service (Xamarin project).

**Comment by anders9ustafsson** [comment]
The sockets support in _Shim_ was originally implemented to support the [fo-dicom](https://github.com/cureos/fo-dicom/) toolkit on Windows 8 and Windows Phone. It is indeed limited, but the basic socket functionality should work on these platforms. The same functionality should also work on Xamarin Android and iOS.

Which platform(s) are you targeting, and more specifically, which parts of the .NET API are you missing in the current implementation? Depending on your requirements, it may be fairly easy to include the functionality you are looking for.

And yes, I also noticed the _Sockets for PCL_ project the other day, but I have not examined it in detail.

**Comment by NVentimiglia** [comment]
Thanks,

The project is a targeting Xamarin Forms for iOS, Android and Windows

**Comment by anders9ustafsson** [comment]
OK, thanks!

_Shim_ is primarily intended as a support library when porting legacy .NET code to PCL, so if you are writing a **new** PCL class library I would primarily recommend that you use a more full-fledged socket solution than _Shim_. 
On the other hand, if you find _Shim_ easier to work with than _Sockets for PCL_, please go ahead to see how far you can get with _Shim_ right now. If you run into obstacles, do not hesitate to report them, and I will do my best to solve these issues. No guarantees that I will be able to fix everything, but it would be great also for _Shim_ if the socket implementation could become more complete.

**Comment by NVentimiglia** [comment]
It is an existing solution, however with the existing solution I have it easy due to MessageWebSocket and ClientWebSocket abstractions which lets me send and receive strings. I may take a look into porting one of these abstractions over later this week.

Thanks for the help. Always nice to see a passionate open source master.

**Comment by NVentimiglia** [comment]
Update, noticed that your socket implementation is incomplete. For instance Socket.BeginReceive is 404.

**Comment by anders9ustafsson** [comment]
Could you add a few more details? Which platform are you testing on? Do you have some code to reproduce the error?

**Comment by NVentimiglia** [comment]
It is a PCL project targeting .net 4.5, win phone 8, win phone silverlight 8, windows 8, Xamarin.Android, Xamarin.iOS.

```
            var socket = new Socket();
            socket.BeginReceive()// Missing. Like most everything else.
```

**Comment by anders9ustafsson** [comment]
OK, sorry, now I see what you mean. As I mentioned, _Shim_ has evolved from very specific needs, where I for example wanted to facilitate porting the _fo-dicom_ library for medical image processing and network I/O to PCL. Therefore several _Shim_ classes such as `Socket` only contains the methods and properties necessary to ensure that the ported library builds.
Ideally, I would like to add a more complete API to the different classes, and I would of course be grateful for any help I can get doing this. For the time being, classes like `Socket` are inevitably incomplete.

**Comment by NVentimiglia** [comment]
I see. Ill just use the sockets-for-pcl library for that then.
