### ISSUE TITLE
Unable to add Nuget package to Silverlight5 project

### ISSUE THREAD

**Issue by nowol** [cureos/shim#32]
Hello,

I'm currently testing your Shim library to see if it can fix an issue I have with the SerializedAttribute class and PCL136/SL5 projects, however I am not able to reference it in my projects.  I cannot find the Shim package if I try to add it using the Visual Studio 'Manage Nuget References' dialog and if I try to add it using the package console I get this error:

```
install-package : Could not install package 'shim 1.0.2.50909'. You are trying to install this package into a project that targets 'Silverlight,Version=v5.0', but the package does not contain any 
assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

Which tells me that a SL5 compatible Dll was not found in the Nuget package but I can see in your source that you have a Silverlight project and that you have a related target="lib\sl5" in your nuspec file so I wanted to confirm with you if SL5 was supported.  

Best regards

**Comment by anders9ustafsson** [comment]
@nowol I have prepared for a 2.0 release with profile 328 / SL5 support, but I have not had time to finalize it yet. I can however prepare a pre-release for you to try out. I'll try to get it published within the next few days or so.

**Comment by nowol** [comment]
That would be great

**Comment by anders9ustafsson** [comment]
@nowol I should point out though, that for Silverlight `[Serializable]` is only declared, there is no implementation available that allows you to perform binary serialization. You will be able to compile code containing e.g. `[Serializable]`, but if you call a serialization method in your SL application, a `PlatformNotSupportedException` will be thrown. 

On .NET and the Xamarin targets, `[Serializable]` is fully supported via their respective framework implementations, but _Shim_ does not provide any implementation for those platforms natively missing it. It has been included in _Shim_ primarily to enable PCL compilation of legacy code bases.

For real serialization, you would need to use for example `[DataContract]` or some third-party serialization solution.

**Comment by nowol** [comment]
Thanks for the info @anders9ustafsson .
Here's what I am trying to achieve: I want to share some classes between net451 projects and PCL/SL5 projects.  Some of the classes uses the `Serializable` attribute to allow binary serialization using `BinaryFormatter`, the binary serialization will only be made from the net451 project but I need the `Serializable` attribute on the shared classes.

The projects structure will look something like this:
- net451
- SL5 project
- PCL136 project
- "Shared Dll" that will contain classes (with `Serializable`) that will be shared between the other 3 projects.

From what I understand a shim of SerializableAttribute will allow me to share my classes and allow binary serialization in the net451 project.

**Comment by anders9ustafsson** [comment]
@nowol Yes, as far as I can tell _Shim_ (2.0) should be sufficient for your purposes.

**Comment by anders9ustafsson** [comment]
@nowol It took a little longer than anticipated, but now I have published a _Shim_ 2.0 pre-release on NuGet, containing among others a _Silverlight 5_ target.

Please give it a try and report any issues you encounter.

Regards,
Anders

**Comment by orck-adrouin** [comment]
Hi,
I tested the new version in SL5 and a PCL136 projects and everything seems to work properly.

thanks.

**Comment by nowol** [comment]
Hi,
I tested the new version in SL5 and a PCL136 projects and everything seems to work properly.

thanks.
