### ISSUE TITLE
Add support for Xamarin.Mac20

### ISSUE THREAD

**Issue by nowol** [cureos/shim#34]
Hi,

I'm testing your library in a new Xamarin Studio V5.10 Mac project and I got this error when I tried to use the SerializableAttribute:

![2015_12_10_14_08_42_2015_12_10_13_38_02_greenshot png_paint](https://cloud.githubusercontent.com/assets/2602451/11725446/b9af154a-9f47-11e5-8797-6ca6c85865eb.png)

Can you add support for the Xamarin.Mac20 target?  As you can see from the screenshot a Mac application uses the portable-net45[...] package however System.Serializable is already defined in Xamarin's Mac dlls.

I tested with an iOS app and I did not have the same issue.

---

It was the first time I used Xamarin Studio so perhaps I did something wrong. Here are the steps to reproduce the issue:
- Open Xamarin Studio
- Create a new Mac app or library
- Add a Nuget reference to Shim
- Put the following code in a cs file: `System.SerializableAttribute e;`

**Comment by anders9ustafsson** [comment]
@nowol I don't have a Xamarin Mac license myself, so I don't think I will be able to create a Mac specific target. I'll keep this open; if someone in the community is willing to donate sufficient funds for me to purchase a license I would be more than happy to add a Mac target to _Shim_ :-)

**Comment by orck-adrouin** [comment]
I no longer need the target Xamarin.Mac20 so I think that you can close the issue for now.

**Comment by nowol** [comment]
I no longer need the target Xamarin.Mac20 so I'll close the issue for now.
