### ISSUE TITLE
System.IO.File

### ISSUE THREAD

**Issue by ncruces** [cureos/shim#37]
Any reason the [`File`](https://github.com/cureos/shim/blob/development/Sources/Shim/IO/File.cs) shim has `ReadAllLines` and `WriteAllText`, but is missing `ReadAllText` and `WriteAllLines`?

**Comment by anders9ustafsson** [comment]
Hello Nuno,

Only reason: pure laziness :-) I have not had any need for those methods myself in the libraries I am maintaining. Thanks for posting the PR, I will look it over as soon as possible. 

Regards,
Anders @ Cureos
