### ISSUE TITLE
Exception - unsupported platform exception (v 2.0.0)

### ISSUE THREAD

**Issue by godrose** [cureos/shim#45]
Steps to repro:
1) Create a PCL project.
1) Install shim 2.0.0
2) use the following code:
`var isEnumerable = typeof(IEnumerable<string>).IsAssignableFrom(propertyInfo.PropertyType)`

Expected: boolean value is evaluated
Actual: Exception is thrown: Unsupported platform exception, message: PCL.

Note: this code works with the previous version 1.0.2.50909.

**Comment by anders9ustafsson** [comment]
@godrose Thanks for reporting. In 2.0, practically all method calls in the PCL library are stubs. You will need to explicitly add a reference to Shim in your application/unit test project to ensure that the correct platform version of Shim is employed. In other words, explicitly add the Shim NuGet package to your application, not just to your PCL project.

**Comment by godrose** [comment]
@anders9ustafsson  Added nuget package to the Unit Tests project. Same issue is reproduced.
I'm using **Profile111**

**Comment by anders9ustafsson** [comment]
@godrose What unit test package are you using, and which platform is it built upon?

**Comment by godrose** [comment]
**NUnit** Currently using 2.6.4. 
3.0.0 doesn't play well with PCL and Universal, from my experience.

**Comment by anders9ustafsson** [comment]
Which platform target? .NET 4, 4.5, or? If you single-click on the Shim assembly in the References of your unit test project and look at its Properties, what is the full path to the referenced assembly?

**Comment by godrose** [comment]
Can't look right now, will talk to you later.
thanks for the support,
@anders9ustafsson

**Comment by anders9ustafsson** [comment]
@godrose Any news on this? Have you got it working by now?

**Comment by godrose** [comment]
No.still doesn't work...

**Comment by anders9ustafsson** [comment]
@godrose OK. Your unit test project, which .NET version is it (4, 4.5, other)? And you have explicitly added the _Shim_ NuGet package to the unit test project? What is the file path of the _Shim_ reference in the unit test project?

**Comment by godrose** [comment]
Hi.
The exception does not reproduce.
Thanks for the support. 
I will upgrade to the latest Shim's version.
Thanks for the great job!
