### ISSUE TITLE
Cant strip assembly

### ISSUE THREAD

**Issue by vbisbest** [cureos/shim#46]
I am getting a build error when compiling for the app store using Xamarin for Visual Studio.

C:\Program Files (x86)\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(673,3): error : Could not strip assembly `/Users/vbisbest/Library/Caches/Xamarin/mtbs/builds/MineChatFormsiOS/b63ac9666622ed5ef9ea329c91871775/obj/iPhone/AppStore/mtouch-cache/64/Build/Shim.dll`.

Ideas?

**Comment by anders9ustafsson** [comment]
@vbisbest Thanks for reporting. Do you have a more detailed stack trace or something?

**Comment by anders9ustafsson** [comment]
@vbisbest Did you manage to resolve this issue?
